# -----------------------GENERATED BY CHAT-GPT-----------------------------

import matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont

# Set up the image canvas
plt.rcParams['figure.dpi'] = 500
width, height = 430, 150
image = Image.new('RGB', (width, height), 'black')
draw = ImageDraw.Draw(image)

# Define the font
try:
    font = ImageFont.truetype("Luminari", 40)
    small_font = ImageFont.truetype("Luminari", 20)
except IOError:
    font = ImageFont.load_default()
    small_font = ImageFont.load_default()

# Draw the book icon (stylized)
book_width, book_height = 40, 55
book_color = (0, 102, 204)  # Blue color
draw.rectangle([50, (height - book_height) // 2, 50 + book_width, (height + book_height) // 2], fill=book_color)
draw.rectangle([60, (height - book_height) // 2 + 10, 60 + book_width, (height + book_height) // 2 + 10], outline='white', width=5)

# ------------------------------TEXT ON IMAGE------------------------------------

# Define the font
try:
    font = ImageFont.truetype("Monospaced", 20)
except IOError:
    font = ImageFont.load_default()

# Define the three lines of text
lines = ["The", "Online library", "Project"]

# Calculate the total height of the text block
total_text_height = sum(font.getbbox(line)[3] - font.getbbox(line)[1] for line in lines)

# Calculate the starting y position
start_y = (height - total_text_height - 10) // 2

# Draw each line of text centered horizontally
current_y = start_y
for line in lines:
    bbox = font.getbbox(line)
    text_width = bbox[2] - bbox[0]
    text_x = (width - text_width - 150) // 2
    draw.text((text_x, current_y), line, fill=(0, 102, 204), font=font)
    current_y += bbox[3] - bbox[1] + 7

# Display the logo
plt.figure(figsize=(10, 3), dpi = 300)
plt.imshow(image)
plt.axis('off')
plt.show()

image.save("C:\\Users\\Raghavendra\\OneDrive\\Desktop\\logo.png")
